version: '3.1'

services:
  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./client:/app
  
  mongo:
    image: mongo:5.0.8
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  server:
    build:
      context: ./server
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./server:/app
